#!/usr/bin/env python3
"""Tool to create a binary-encoded hints file for the "IBD-Booster" proposal.

The resulting data is a bit-vector of all transaction outputs ever created
up to block number N, where each bit indicates the answer to the question
"Is this transaction output part of the UTXO set at block height N?".

The input UTXO set database for a certain snapshot at height N
can be generated by Bitcoin Core with the following commands:
$ ./build/bin/bitcoin-cli -rpcclienttimeout=0 -named dumptxoutset $PWD/utxos.dat rollback=N
$ ./contrib/utxo-tools/utxo_to_sqlite.py utxos.dat utxos.sqlite3
"""
import argparse
from pathlib import Path
import sqlite3
import sys
import time

from bitcoin_primitives import CBlock, from_binary
import pbk

# uv run tx-db.py -v /Users/node/Library/Application\ Support/Bitcoin tx-db.sqlite --chain=signet

def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('node_datadir', help='path to bitcoin data directory (must be from a non-pruned node)')
    parser.add_argument('utxos_sqlite_db', help='path to UTXO dump in SQLite3 format')
    parser.add_argument('-v', '--verbose', action='store_true', help='show more detailed conversion stats on each block')
    parser.add_argument('--chain', default='mainnet', help='chain to use (mainnet by default; allowed values: mainnet, signet, testnet4, testnet, regtest)')

    args = parser.parse_args()

    if not Path(args.node_datadir).exists():
        print(f"Error: provided input directory '{args.node_datadir}' doesn't exist.")
        sys.exit(1)

    chaintype = {
        'mainnet':  pbk.ChainType.MAINNET,
        'signet':   pbk.ChainType.SIGNET,
        'testnet4': pbk.ChainType.TESTNET_4,
        'testnet':  pbk.ChainType.TESTNET,
        'regtest':  pbk.ChainType.REGTEST,
    }.get(args.chain)
    if chaintype is None:
        print(f"Error: provided invalid chain type '{args.chain}'.")
        sys.exit(1)

    datadir = Path(args.node_datadir)
    print(f"Using node datadir: {datadir}")
    print("Loading chain manager... ", end='', flush=True)
    chain_path = datadir / args.chain
    print(f"Loading chain from {chain_path} ...")
    chainman = pbk.load_chainman(chain_path, chaintype)
    print("done.")

    print(args)

    start = 0 #chainman.get_block_index_from_genesis()
    tip_height = chainman.get_block_index_from_tip().height

    print (f"Tip height: {tip_height}")

    for block_height in range(0, tip_height+1):
        start_time = time.time()
        print(f"Processing block {block_height}... ", flush=True)
        block_index = chainman.get_block_index_from_height(block_height)
        block_data = chainman.read_block_from_disk(block_index).data
        block = from_binary(CBlock, block_data)
        #assert block.is_valid()
        outputs_bitmap = []
        outputs_in_utxo_set = 0

        for tx in block.vtx:
            tx.calc_sha256()
            txid = tx.sha256
            print(f"txid: {txid[::-1].hex()}")
            print(f"version: {tx.version}")
            print(f"locktime: {tx.nLockTime}")

            print(f"--- txout")
            for txout in tx.vout:
                print(f"--- --- nValue: {txout.nValue}")
                print(f"--- --- scriptPubKey: {txout.scriptPubKey.hex()}")
            
            print(f"--- txin")
            
            for txin in tx.vin:
                print(f"--- --- prevout: {txin.prevout}")
                print(f"--- --- scriptSig: {txin.scriptSig.hex()}")
                print(f"--- --- nSequence: {txin.nSequence}")

            print(f"--- witness:")
            for witness in tx.wit.vtxinwit:
                print(f"--- --- witness: {witness}")

if __name__ == "__main__":
    main()